import type { BrandConfig, Product } from '../types';
import { officialLogoUrl, socialMediaAssets } from './socialMedia';

export const brandConfig: BrandConfig = {
  name: 'TAPPINO',
  tagline: 'Sip. Chill. Repeat. ❤️',
  subTagline: 'Premium Cold Coffee & Hot Brews',
  startingPrice: '₹39',
  city: 'Nagpur',
  locationArea: 'IT Park',
  state: 'Maharashtra',
  country: 'India',
  fullLocationDisplay: 'IT Park, Nagpur, Maharashtra',
  logoUrl: officialLogoUrl,
  instagram: {
    handle: '@officialtappino',
    url: 'https://www.instagram.com/officialtappino/',
    dmUrl: 'https://ig.me/m/officialtappino',
    bioLine1: 'Freshly Brewed | Rich Taste',
    bioLine2: '📍 IT Park, Nagpur',
    bioLine3: '📩 DM for Orders & Collaborations',
  },
  maps: {
    embedQuery: 'IT+Park+Nagpur+Maharashtra',
    directionsUrl: 'https://www.google.com/maps/search/?api=1&query=IT+Park+Nagpur+Maharashtra',
  },
  features: [
    {
      title: 'Freshly Brewed',
      description: 'Slow-crafted in small batches daily for unmatched aroma and rich depth.',
      tag: '01 / CRAFT',
    },
    {
      title: 'Rich Taste',
      description: 'Bold espresso roast balanced with velvety texture that never tastes watered down.',
      tag: '02 / FLAVOR',
    },
    {
      title: 'Chilled to Perfection',
      description: 'Sub-zero frosted brewing that stays thick, icy, and refreshing to the last sip.',
      tag: '03 / TEMPERATURE',
    },
    {
      title: 'Starting at ₹39',
      description: 'Ultra-premium café taste at an honest, accessible student-and-creator-friendly price.',
      tag: '04 / VALUE',
    },
  ],
  story: {
    heading: 'MORE THAN COFFEE.',
    subheading: 'Born from the energy of Nagpur’s IT Park.',
    paragraphs: [
      'Tappino was created with one simple conviction: exceptional cold coffee should not be an overpriced luxury or a generic café afterthought.',
      'We brew every cup fresh, with deep roasted espresso notes, thick velvety creaminess, and an honest obsession for real flavor. No artificial shortcuts, no watered-down compromises.',
      'Whether you are taking a break from coding sprints in IT Park, catching up with friends during sunset, or grabbing that ice-cold energy boost on the go — Tappino is built for you.',
    ],
    stats: [
      { label: 'Signature Brews', value: '100% Fresh' },
      { label: 'Nagpur Hub', value: 'IT Park' },
      { label: 'Cold Coffee From', value: '₹39' },
      { label: 'Brand Motto', value: 'Sip. Chill. Repeat.' },
    ],
  },
};

export const products: Product[] = [
  {
    id: 'signature-cold-coffee',
    name: 'Tappino Signature Cold Coffee',
    category: 'cold',
    subtitle: 'The Nagpur Hero Cold Brew',
    description: 'Our iconic flagship cold coffee. Double-filtered espresso poured over chilled whole milk with a thick velvety froth and signature caramel undertones.',
    price: 'Starting at ₹39',
    badge: 'HERO OBSESSION',
    isHero: true,
    tastingNotes: ['Velvet Espresso', 'Caramel Crema', 'Chilled Silk'],
    temperature: 'Iced & Chilled',
    intensity: 4,
    image: '/images/products/hero_cold_coffee.jpg',
    customization: {
      sweetnessOptions: ['Balanced (Standard)', 'Less Sweet', 'No Added Sugar', 'Extra Sweet'],
      iceOptions: ['Chilled (Standard)', 'Extra Ice', 'Less Ice'],
      extraShots: true,
      milkOptions: ['Standard Cream Milk', 'Oat Milk (+₹20)', 'Almond Milk (+₹20)'],
    },
  },
  {
    id: 'hazelnut-cold-coffee',
    name: 'Hazelnut Velvet Cold Coffee',
    category: 'cold',
    subtitle: 'Nutty & Smooth Delight',
    description: 'Rich cold coffee infused with aromatic roasted hazelnut essence and topped with golden whipped cream and caramelized hazelnut praline dust.',
    price: '₹59',
    badge: 'BESTSELLER',
    tastingNotes: ['Toasted Hazelnut', 'Whipped Foam', 'Roasted Cocoa'],
    temperature: 'Iced & Chilled',
    intensity: 3,
    image: '/images/products/hazelnut_cold.jpg',
    customization: {
      sweetnessOptions: ['Balanced (Standard)', 'Less Sweet', 'Extra Sweet'],
      iceOptions: ['Chilled (Standard)', 'Extra Ice'],
      extraShots: true,
      milkOptions: ['Standard Cream Milk', 'Oat Milk (+₹20)'],
    },
  },
  {
    id: 'dark-mocha-espresso-cold',
    name: 'Dark Mocha Cold Fusion',
    category: 'cold',
    subtitle: 'Deep Cocoa & Bold Crema',
    description: 'Artisan dark cocoa ganache layered with an intense double espresso shot over crystal sphere ice and cold textured milk.',
    price: '₹69',
    badge: 'BOLD OBSESSION',
    tastingNotes: ['70% Dark Chocolate', 'Smoked Cocoa', 'Intense Espresso'],
    temperature: 'Iced & Chilled',
    intensity: 5,
    image: '/images/products/dark_mocha.jpg',
    customization: {
      sweetnessOptions: ['Dark & Bitter (Low Sugar)', 'Balanced', 'Sweet Tooth'],
      iceOptions: ['Crystal Sphere Ice', 'Crushed Ice'],
      extraShots: true,
      milkOptions: ['Standard Cream Milk', 'Oat Milk (+₹20)'],
    },
  },
  {
    id: 'artisan-hot-cappuccino',
    name: 'Artisan Velvet Hot Cappuccino',
    category: 'hot',
    subtitle: 'Steaming Microfoam Perfection',
    description: 'Freshly pulled single-origin espresso crowned with dense, silky microfoam and bespoke rosetta latte art. Warm, comforting, and deeply aromatic.',
    price: '₹49',
    badge: 'FRESH ROAST',
    tastingNotes: ['Almond Cream', 'Muted Honey', 'Dark Roast'],
    temperature: 'Steaming Hot',
    intensity: 4,
    image: '/images/products/hot_cappuccino.jpg',
    customization: {
      sweetnessOptions: ['No Sugar (Purist)', '1 Sugar', '2 Sugars', 'Brown Sugar'],
      iceOptions: [],
      extraShots: true,
      milkOptions: ['Whole Milk', 'Skim Milk', 'Oat Milk (+₹20)'],
    },
  },
  {
    id: 'signature-cold-cascade',
    name: 'Tappino Cold Cascade Pour',
    category: 'special',
    subtitle: 'The Barista Reserve',
    description: 'High-speed pulled espresso shaken with iced cream milk and poured table-side with a mesmerizing cascading crema ripple.',
    price: '₹79',
    badge: 'LIMITED RESERVE',
    tastingNotes: ['Layered Crema', 'Frosted Vanilla', 'Bold Body'],
    temperature: 'Nitro Cold',
    intensity: 5,
    image: '/images/products/signature_pour.jpg',
    customization: {
      sweetnessOptions: ['Balanced', 'Less Sweet', 'Zero Sugar'],
      iceOptions: ['Sub-Zero Cold', 'Standard Ice'],
      extraShots: true,
      milkOptions: ['Whole Cream Milk'],
    },
  },
];

// Export real social media assets
export const instagramPosts = socialMediaAssets;
