import type { SocialMediaAsset } from '../types';

export const officialLogoUrl = 'https://res.cloudinary.com/dsqxboxoc/image/upload/v1786688501/officialtappino_14050523_114952927_q7nlwe.jpg';

export const socialMediaAssets: SocialMediaAsset[] = [
  {
    id: 'media-01-featured',
    type: 'video',
    url: 'https://res.cloudinary.com/dsqxboxoc/video/upload/v1786688513/nagpur__shahar_14050523_115005604_jsoffd.mp4',
    posterUrl: 'https://res.cloudinary.com/dsqxboxoc/video/upload/so_1,q_auto,w_800/v1786688513/nagpur__shahar_14050523_115005604_jsoffd.jpg',
    title: 'Nagpur Shahar Vibe & Fresh Pour',
    creator: 'nagpur__shahar',
    caption: 'Nagpur city energy paired with Tappino’s signature frosted cold brew. Freshly brewed in small batches at IT Park. Sip. Chill. Repeat. ❤️ #Tappino #Nagpur',
    likes: '4,820',
    tag: 'FEATURED REEL',
    date: 'Trending',
    instagramUrl: 'https://www.instagram.com/officialtappino/',
    featured: true,
    aspectRatio: 'vertical',
  },
  {
    id: 'media-02-swirl',
    type: 'video',
    url: 'https://res.cloudinary.com/dsqxboxoc/video/upload/v1786688506/officialtappino_14050523_114955418_denvp0.mp4',
    posterUrl: 'https://res.cloudinary.com/dsqxboxoc/video/upload/so_1,q_auto,w_600/v1786688506/officialtappino_14050523_114955418_denvp0.jpg',
    title: 'Signature Espresso Swirl',
    creator: 'officialtappino',
    caption: 'Double espresso extraction poured slow over chilled whole milk with rich microfoam crema. Starting @ ₹39! 🧋✨',
    likes: '3,150',
    tag: '#FreshEspresso',
    date: 'Recent',
    instagramUrl: 'https://www.instagram.com/officialtappino/',
    aspectRatio: 'vertical',
  },
  {
    id: 'media-03-chill',
    type: 'video',
    url: 'https://res.cloudinary.com/dsqxboxoc/video/upload/v1786688505/sonnaaaa08.__14050523_115007134_rwozp3.mp4',
    posterUrl: 'https://res.cloudinary.com/dsqxboxoc/video/upload/so_1,q_auto,w_600/v1786688505/sonnaaaa08.__14050523_115007134_rwozp3.jpg',
    title: 'Squad Chill & Cold Coffee',
    creator: 'sonnaaaa08._',
    caption: 'Afternoon coffee run with the crew. Sub-zero frosty cold coffee that never tastes watered down! 🤎❄️',
    likes: '2,640',
    tag: '#ChillMoments',
    date: '2d ago',
    instagramUrl: 'https://www.instagram.com/officialtappino/',
    aspectRatio: 'vertical',
  },
  {
    id: 'media-04-image',
    type: 'image',
    url: 'https://res.cloudinary.com/dsqxboxoc/image/upload/v1786688505/officialtappino_14050523_115008693_xem4gl.jpg',
    title: 'The Tappino Signature Cup',
    creator: 'officialtappino',
    caption: 'Crafted in small batches with bold roast single-origin beans and velvety cold milk. Authentic coffee passion in every cup.',
    likes: '3,890',
    tag: '#TappinoCup',
    date: 'Featured',
    instagramUrl: 'https://www.instagram.com/officialtappino/',
    aspectRatio: 'square',
  },
  {
    id: 'media-05-barista',
    type: 'video',
    url: 'https://res.cloudinary.com/dsqxboxoc/video/upload/v1786688505/officialtappino_14050523_115001523_giidfa.mp4',
    posterUrl: 'https://res.cloudinary.com/dsqxboxoc/video/upload/so_1,q_auto,w_600/v1786688505/officialtappino_14050523_115001523_giidfa.jpg',
    title: 'Barista Craft in Motion',
    creator: 'officialtappino',
    caption: 'Handcrafted with precision. Every cup delivers rich espresso body and velvety microfoam texture.',
    likes: '2,920',
    tag: '#BaristaCraft',
    date: '4d ago',
    instagramUrl: 'https://www.instagram.com/officialtappino/',
    aspectRatio: 'vertical',
  },
  {
    id: 'media-06-itpark',
    type: 'video',
    url: 'https://res.cloudinary.com/dsqxboxoc/video/upload/v1786688505/adilakhtar7.9_14050523_114956863_bq9ttf.mp4',
    posterUrl: 'https://res.cloudinary.com/dsqxboxoc/video/upload/so_1,q_auto,w_600/v1786688505/adilakhtar7.9_14050523_114956863_bq9ttf.jpg',
    title: 'IT Park Coding Sprint Fuel',
    creator: 'adilakhtar7.9',
    caption: 'Fueling through work & code sprints in IT Park Nagpur with Tappino’s thick cold coffee 💻⚡',
    likes: '1,780',
    tag: '#ITParkNagpur',
    date: '5d ago',
    instagramUrl: 'https://www.instagram.com/officialtappino/',
    aspectRatio: 'vertical',
  },
  {
    id: 'media-07-cinematic',
    type: 'video',
    url: 'https://res.cloudinary.com/dsqxboxoc/video/upload/v1786688502/solankicine_14050523_115000081_vn5ahl.mp4',
    posterUrl: 'https://res.cloudinary.com/dsqxboxoc/video/upload/so_1,q_auto,w_600/v1786688502/solankicine_14050523_115000081_vn5ahl.jpg',
    title: 'Cinematic Brew Aesthetic',
    creator: 'solankicine',
    caption: 'Pure coffee aesthetic in Nagpur. Sub-zero frosty extraction captured in high definition ☕🎬',
    likes: '3,410',
    tag: '#CoffeeCinematics',
    date: '1w ago',
    instagramUrl: 'https://www.instagram.com/officialtappino/',
    aspectRatio: 'vertical',
  },
];
